YAAS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('not_allowed', TemplateView.as_view(template_name='not_allowed.html'),
         name='not_allowed'),
    path('auction_not_active', TemplateView.as_view(template_name='auction_not_active.html'),
         name='auction_not_active'),
    path('yaasapp/', include('django.contrib.auth.urls')),
    path('yaasapp/', include('yaasapp.urls')),
    url(r'^admin/', admin.site.urls),
]

yaasapp/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers
from yaasapp.views import UserViewSet, AuctionViewSet, api_bid, \
    change_currency, email_history
from . import views

app_name ='yaasapp'

# Routers provide an easy way of automatically determining the URL conf.
# this is for the API
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('auctions', AuctionViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('profile_update', views.update_profile, name='profile_update'),
    path('profile_create', views.create_profile, name='profile_create'),
    path('change_password', views.change_password, name='change_password'),
    path('create_auction', views.create_auction, name='create_auction'),
    path('update_auction/<int:auction_id>', views.update_auction,
         name='update_auction'),
    path('manage_auctions', views.AuctionManagementView.as_view(),
         name='manage_auction'),
    path('ban_auction/<int:auction_id>', views.ban_auction, name='ban_auction'),
    path('active_auction/<int:auction_id>', views.active_auction, name='active_auction'),
    path('active_auction_list', views.ActiveAuctionsView.as_view(),
         name='active_auction_list'),
    path('search_auction_by_title', views.search_auction_by_title, name='search_auction_by_title'),
    path('save_auction', views.save_auction, name='save_auction'),
    path('bid/<int:auction_id>', views.bid, name='bid'),
    path('resolve_auction', views.resolve_auction, name='resolve_auction'),
    path('update_auction_seller/<int:auction_id>', views.update_auction_without_login, name='update_auction_seller'),
    url(r'^api/', include(router.urls)),
    path('api/auction/<int:auction_id>', views.auction_by_id, name='auction_by_id'),
    path('api/bid', api_bid),
    path('generatedata', views.generatedata, name='generate_data'),
    path('language/<slug:lang_code>', views.change_language, name='language'),
    path('change_currency/<int:auction_id>', change_currency, name='change_currency'),
    path('email_history', email_history, name='email_history'),
]

yaasapp/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from datetime import datetime, timedelta, timezone, date
from django.utils.translation import gettext as _

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=40, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def clean(self):
        if not self.user.email:
            raise ValidationError(_('The email should not be empty'))

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwarg):
    instance.profile.save()


class Auction(models.Model):
    STATE = (
        ('ACTIVE', 'active'),
        ('BANNED', 'banned'),
        ('DUE', 'due'),
        ('ADJUCATED', 'adjudicated'),
        ('DEFAULT', 'default')
        ,
    )

    CURRENCY = (
        ('USD', 'usd'),
        ('SEK', 'sek'),
        ('GBP', 'gbp'),

    )
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=60, blank=False)
    description = models.TextField(max_length=500, blank=False)
    min_price = models.FloatField(blank=False, default=1)
    state = models.CharField(max_length=1, choices=STATE, default='DEFAULT')
    post_date = models.DateField(default=date.today())
    deadline = models.DateField(default=date.today()+timedelta(days=3))
    currency = models.CharField(max_length=1, choices=CURRENCY, default='USD')
    currency_value = models.FloatField(blank=True, default=1)

    def clean(self):
        if self.min_price < 1:
            raise ValidationError(_('The minimum price should be at least 1'))
        elif self.deadline < self.post_date + timedelta(days=3):
            raise ValidationError(_('The deadline should be 3 days after the '
                                    'day you posted it'))


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    date = models.DateTimeField(blank=False, default=datetime.now())
    value = models.DecimalField(blank=False, decimal_places=2, max_digits=1000)

yaasapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from yaasapp.models import Profile, Auction, Bid


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date')


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField()
    # bio = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',
                  'birth_date', 'password1', 'password2')


class AuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ('title', 'description', 'min_price', 'deadline')


class AuctionUpdateForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ('description', )


class ConfAuctionCreationForm(forms.Form):
    CHOICES = [(x, x) for x in ("Yes", "No")]
    option = forms.ChoiceField(choices=CHOICES)

    title = forms.CharField(widget=forms.HiddenInput())
    description = forms.CharField(widget=forms.HiddenInput())
    min_price = forms.FloatField(widget=forms.HiddenInput())
    deadline = forms.DateField(widget=forms.HiddenInput())


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ('value',)

yaasapp/views.py
import os
from _decimal import Decimal
from datetime import datetime, timedelta, timezone, date

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core import mail
from django.core.mail import send_mail
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views import generic
from django.views.generic.list import ListView
from rest_framework import viewsets
from rest_framework.authentication import BasicAuthentication
from rest_framework.decorators import api_view, renderer_classes, \
    authentication_classes, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from YAAS.settings import EMAIL_FILE_PATH
from yaasapp import data
from yaasapp.data import mydata
from yaasapp.forms import UserForm, ProfileForm, SignUpForm, AuctionForm, \
    AuctionUpdateForm, ConfAuctionCreationForm, BidForm
from yaasapp.models import Profile, Auction, Bid
from yaasapp.serializers import ProfileSerializer, AuctionSerializer, \
    BidSerializer
from yaasapp.utils import util_send_mail, util_currency_convert


def index(request):
    if request.user.is_authenticated:
        return HttpResponse("Hello, world. You're at YAAS app index")
    else:
        return HttpResponse("You are not authenticated")

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            #return redirect('yaasapp:index')
            return redirect('home')
        else:
            if not user_form.data['email']:
                messages.error(request, _('The email field should not be empty.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'yaasapp/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


def create_profile(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request,
                _('Your profile was successfully created!'))
            return redirect('home')
        else:
            messages.error(request,
                _('Please correct the error below.'))
    else:
        form = SignUpForm()
    return render(request, 'yaasapp/signup.html', {
        'form': form
    })

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('home')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'yaasapp/change_password.html', {
        'form': form
    })

@login_required
def create_auction(request):
    if request.method == 'POST':
        auction_form = AuctionForm(request.POST)
        if auction_form.is_valid():
            form = ConfAuctionCreationForm({'title': auction_form.cleaned_data.get('title'),
                                           'description': auction_form.cleaned_data.get('description'),
                                           'min_price': auction_form.cleaned_data.get('min_price'),
                                           'deadline': auction_form.cleaned_data.get('deadline')})

            """
            auction = auction_form.save(commit=False)
            auction.seller = request.user
            auction.state = 'ACTIVE'
            auction_form.save()
            messages.success(request,
                             'Your auction was successfully created!')
            send_mail(
                'Auction creation',
                'Your auction was successfully created!',
                'yaasapp@yopmail.com',
                [request.user.email],
                fail_silently=False,
            )
            """
            #return redirect('home')
            return render(request, 'yaasapp/conf_auction.html', {'form': form})
        else:
            messages.error(request, 'Please correct the error below : ')
            '''
            if auction_form.data['deadline'] < (datetime.now(timezone.utc) + \
                    timedelta(days=3)).strftime('%Y-%m-%d %H:%M:%S'):
                    messages.error(request, _('The deadline should be 3 days after the day you posted it'))
            '''

    else:
        auction_form = AuctionForm()
    return render(request, 'yaasapp/create_auction.html', {
        'auction_form': auction_form
    })

@login_required
def save_auction(request):
    option = request.POST.get('option', 'No')
    if option == 'Yes':
        title = request.POST.get('title')
        description = request.POST.get('description')
        min_price = request.POST.get('min_price')
        deadline = request.POST.get('deadline')
        auction = Auction(title=title,
                          description=description,
                          seller=request.user,
                          min_price=min_price,
                          deadline=deadline,
                          state='ACTIVE')
        auction.currency_value = float(auction.min_price)*float(util_currency_convert(auction.currency))
        auction.save()
        messages.success(request,
                         'Your auction was successfully created!')
        domain = request.META['HTTP_HOST']
        util_send_mail('Auction creation', f'Your auction has successfully been created! {domain}/yaasapp/update_auction_seller/{auction.id}', request.user.email)
        return redirect('home')
    else:
        messages.success(request,
                         'Your auction was not created!')
        return redirect('home')

@login_required
def update_auction(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    if request.method == 'POST':
        if auction.seller == request.user:
            if auction.state == 'ACTIVE':
                auction_form = AuctionUpdateForm(request.POST, instance=auction)
                if auction_form.is_valid():
                    auction_form.save()
                    messages.success(request,
                                     'Your auction was successfully updated!')
                    return redirect('home')
                else:
                    messages.error(request, _('Please correct the error below.'))
            else:
                return redirect('auction_not_active')
        else:
            return redirect('not_allowed')
    else:
        if auction.seller == request.user:
            if auction.state == 'ACTIVE':
                auction_form = AuctionUpdateForm(instance=auction)
            else:
                return redirect('auction_not_active')
        else:
            return redirect('not_allowed')
    return render(request, 'yaasapp/update_auction.html', {
        'auction_form': auction_form
    })


def update_auction_without_login(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    if auction.state == 'ACTIVE':
        if request.method =='POST':
            auction_form = AuctionUpdateForm(request.POST, instance=auction)
            if auction_form.is_valid():
                auction_form.save()
                messages.success(request,
                                 'Your auction was successfully updated!')
                return redirect('home')
            else:
                messages.error(request, _('Please correct the error below.'))
        else:
            auction_form = AuctionUpdateForm(instance=auction)
    else:
        return redirect('auction_not_active')
    return render(request, 'yaasapp/update_auction.html', {
        'auction_form': auction_form
    })


@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class AuctionManagementView(generic.ListView):
    model = Auction
    template_name = 'yaasapp/manager_interface.html'
    context_object_name = 'active_auctions'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Question.objects.order_by('-pub_date')[:5]
        return Auction.objects.filter(
            #Q(state='ACTIVE') | Q(state='BANNED')
            state='ACTIVE'
        )

    def get_context_data(self, **kwargs):
        context = super(AuctionManagementView, self).get_context_data(**kwargs)

yaasapp/templates/yaasapp/bid.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h2>Bid on this auction</h2>

{% if messages %}
      <div class="messages">
        {% for message in messages %}
          <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %}
      </div>
{% endif %}

<h3>Description :</h3>
<textarea readonly>{{ description }}</textarea>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>

{% endblock %}

yaasapp/templates/yaasapp/change_password.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>Change your password</h1>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
    {{ field.label_tag }}<br>
    {{ field }}
    {% if field.help_text %}
      <small style="color: grey">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Save changes</button>
</form>
{% endblock %}

yaasapp/templates/yaasapp/conf_auction.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <form method="post" action="{% url 'yaasapp:save_auction' %}">
        {% csrf_token %}
        <h2>Are you sure you want to submit this auction ? </h2>
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock %}

yaasapp/templates/yaasapp/create_auction.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h2>{% trans "Create a new auction" %}</h2>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{auction_form.non_field_errors}}

    <form method="post">
        {% csrf_token %}
        {% for field in auction_form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}

          </p>
        {% endfor %}
    <button type="submit">Create</button>
    </form>
{% endblock %}

yaasapp/templates/yaasapp/email_history.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h2>{% trans "Email history" %}</h2>
    <hr>
    <br>
    {% if emails %}
        {% for email in emails %}
            <p>{{ email }}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>{% trans "There is no emails" %}</p>
    {% endif %}
{% endblock %}

yaasapp/templates/yaasapp/manager_interface.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <H1>Management Interface</H1>

    <h2 style="color: green">Active auctions</h2>
    {% if active_auctions %}
        {% for auction in active_auctions %}
            {% if auction.state == 'ACTIVE'%}
                <hr>
                <h3>Title : {{ auction.title }}</h3>
                <p>Description : {{ auction.description }}</p>
                <a href="{% url 'yaasapp:ban_auction' auction.id %}">Ban this auction</a>
            {% endif %}
        {% endfor %}
    {% else %}
        <p> There is no active auctions.</p>
    {% endif %}

    <br>
    <h2 style="color: red">Banned auctions</h2>
    {% if banned_auctions %}
        {% for auction in banned_auctions %}
            {% if auction.state == 'BANNED'%}
                <h3>Title : {{ auction.title }}</h3>
                <p>Description : {{ auction.description }}</p>
                <a href="{% url 'yaasapp:active_auction' auction.id %}">Active this auction</a>
            {% endif %}
        {% endfor %}
    {% else %}
        <p> There is no banned auctions.</p>
    {% endif %}
{% endblock %}

yaasapp/templates/yaasapp/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <form method="post">
      {% csrf_token %}
        <!-- fields of the user form -->
        {% for field in user_form %}
        <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}

        <!-- fields of the profile form -->
        {% for field in profile_form %}
        <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
      <button type="submit">Save changes</button>
    </form>
{% endblock %}

yaasapp/templates/yaasapp/search_active_auctions.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h2>{% trans "Active auctions" %}</h2>
    <br>
    {% if active_auctions %}
        {% for auction in active_auctions %}
            {% if auction.state == 'ACTIVE'%}
                <hr>
                <h3>Title : {{ auction.title }}</h3>
                <p>Description : {{ auction.description }}</p>
                <p>Current price (EUR): {{ auction.min_price }}</p>
                <p>Current price ({{ auction.currency }}) : {{ auction.currency_value |floatformat:2}}</p>
                <form action="{% url 'yaasapp:change_currency' auction.id %}">
                {% csrf_token %}
                <table>
                <thead>
                <th>
                  <select name="currency">
                      {% if auction.currency == 'USD' %}
                        <option value="GBP">GBP</option>
                        <option value="SEK">SEK</option>
                      {% elif auction.currency == 'GBP' %}
                          <option value="USD">USD</option>
                          <option value="SEK">SEK</option>
                      {% else %}
                          <option value="USD">USD</option>
                          <option value="GBP">GBP</option>
                      {% endif %}
                  </select>
                </th>
                <th>
                  <input type="submit" value="Change currency">
                </th>
                </thead>
                </table>
                </form>
                {% if auction.seller != user %}
                    <a href="{% url 'yaasapp:bid' auction.id %}">Bid on this auction</a>
                {% else %}
                    <p style="color: red">You cannot bid on this auction because you posted it !</p>
                    <a href="{% url 'yaasapp:update_auction' auction.id%}">Update auction</a>
                {% endif %}
            {% endif %}
        {% endfor %}
{#        <br>#}
{#        <br>#}
{#        {% if is_paginated %}#}
{#        <div class="pagination">#}
{#            <span class="page-links">#}
{#                {% if page_obj.has_previous %}#}
{#                    <a href="/yaasapp/active_auction_list?page={{ page_obj.previous_page_number }}">{% trans "previous"%}</a>#}
{#                {% endif %}#}
{#                <span class="page-current">#}
{#                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}#}
{#                </span>#}
{#                {% if page_obj.has_next %}#}
{#                    <a href="/yaasapp/active_auction_list?page={{ page_obj.next_page_number }}">{% trans "next"%}</a>#}
{#                {% endif %}#}
{#            </span>#}
{#        </div>#}
{#    {% endif %}#}
    {% else %}
    <p> There is no active auctions.</p>
    {% endif %}
{% endblock %}

yaasapp/templates/yaasapp/search_auctions_by_title.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h2>Search Auction by title</h2>
<br>
<br>

<form action="{% url 'yaasapp:search_auction_by_title' %}" method="get">
    <input type="text" name="title" type="text"/>
    <button type="submit" >Search</button>
</form>

{% if auctions %}
    <h3>Results</h3>
{% for auction in auctions %}
    <hr>
    <h3>Title : {{ auction.title }}</h3>
    <p>Description : {{ auction.description }}</p>
    <p>Current price (EUR): {{ auction.min_price }}</p>
    <p>Current price ({{ auction.currency }}) : {{ auction.currency_value |floatformat:2}}</p>
    <form action="{% url 'yaasapp:change_currency' auction.id %}">
    {% csrf_token %}
    <table>
    <thead>
    <th>
      <input type="hidden" name="is_search_by_title" value="True">
      <select name="currency">
          {% if auction.currency == 'USD' %}
            <option value="GBP">GBP</option>
            <option value="SEK">SEK</option>
          {% elif auction.currency == 'GBP' %}
              <option value="USD">USD</option>
              <option value="SEK">SEK</option>
          {% else %}
              <option value="USD">USD</option>
              <option value="GBP">GBP</option>
          {% endif %}
      </select>
    </th>
    <th>
      <input type="submit" value="Change currency">
    </th>
    </thead>
    </table>
    </form>
    {% if auction.seller != user %}
        <a href="#">Bid on this auction</a>
    {% else %}
        <p style="color: red">You cannot bid on this auction because you posted it !</p>
        <a href="{% url 'yaasapp:update_auction' auction.id%}">Update auction</a>
    {% endif %}
{% endfor %}
{% endif %}
{% endblock %}

yaasapp/templates/yaasapp/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

yaasapp/templates/yaasapp/update_auction.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
    <h2>Update auction</h2>
    {{auction_form.non_field_errors}}

    <form method="post">
        {% csrf_token %}
        {% for field in auction_form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}

          </p>
        {% endfor %}
    <button type="submit">Update</button>
    </form>
{% endblock %}