YAAS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('not_allowed', TemplateView.as_view(template_name='not_allowed.html'),
         name='not_allowed'),
    path('auction_not_active', TemplateView.as_view(template_name='auction_not_active.html'),
         name='auction_not_active'),
    path('yaasapp/', include('django.contrib.auth.urls')),
    path('yaasapp/', include('yaasapp.urls')),
    url(r'^admin/', admin.site.urls),
]

yaasapp/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers
from yaasapp.views import UserViewSet, AuctionViewSet, api_bid, \
    change_currency, email_history
from . import views

app_name ='yaasapp'

# Routers provide an easy way of automatically determining the URL conf.
# this is for the API
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('auctions', AuctionViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('profile_update', views.update_profile, name='profile_update'),
    path('profile_create', views.create_profile, name='profile_create'),
    path('change_password', views.change_password, name='change_password'),
    path('create_auction', views.create_auction, name='create_auction'),
    path('update_auction/<int:auction_id>', views.update_auction,
         name='update_auction'),
    path('manage_auctions', views.AuctionManagementView.as_view(),
         name='manage_auction'),
    path('ban_auction/<int:auction_id>', views.ban_auction, name='ban_auction'),
    path('active_auction/<int:auction_id>', views.active_auction, name='active_auction'),
    path('active_auction_list', views.ActiveAuctionsView.as_view(),
         name='active_auction_list'),
    path('search_auction_by_title', views.search_auction_by_title, name='search_auction_by_title'),
    path('save_auction', views.save_auction, name='save_auction'),
    path('bid/<int:auction_id>', views.bid, name='bid'),
    path('resolve_auction', views.resolve_auction, name='resolve_auction'),
    path('update_auction_seller/<int:auction_id>', views.update_auction_without_login, name='update_auction_seller'),
    url(r'^api/', include(router.urls)),
    path('api/auction/<int:auction_id>', views.auction_by_id, name='auction_by_id'),
    path('api/bid', api_bid),
    path('generatedata', views.generatedata, name='generate_data'),
    path('language/<slug:lang_code>', views.change_language, name='language'),
    path('change_currency/<int:auction_id>', change_currency, name='change_currency'),
    path('email_history', email_history, name='email_history'),
]

templates/auction_not_active.html
<!-- templates/home.html -->
{% extends './base.html' %}
{% load i18n %}

{% block content %}
    <a href="{% url 'home' %}">{% trans "Home" %}</a>
    <br>
    <p>You cannot update the auction because it is not active anymore.</p>
{% endblock %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}YAAS !{% endblock %}</title>
</head>
<body>
  <main>
    {% load i18n %}
  <hr>
     <h1>{% trans "YAAS ! Yet An other Auction Service" %}</h1>
      {% get_current_language as LANGUAGE_CODE %}
      {% if LANGUAGE_CODE == 'en' %}
          <form action="{% url "yaasapp:language" 'fr' %}" method="get">
              <button type="submit">FR</button>
          </form>
      {% else %}
          <form action="{% url "yaasapp:language" 'en' %}" method="get">
            <button type="submit">EN</button>
          </form>
      {% endif %}
    <br>
    <a href="{% url 'home' %}">{% trans "Home" %}</a>
    <br>
  <br>
  <hr>
  <br>

    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends './base.html' %}
{% load i18n %}

{% block content %}
    {% if user.is_authenticated %}
        {% trans "Welcome" %} {{ user.first_name }} !
        <p><a href="{% url 'logout' %}">{% trans "logout" %}</a></p>
    {% else %}
      <p>{% trans "You are not logged in" %}</p>
      <a href="{% url 'login' %}">{% trans "login" %}</a>
    {% endif %}

    {% if messages %}
      <div class="messages">
        {% for message in messages %}
          <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %}
      </div>
    {% endif %}

    <br>
    {% if user.is_superuser %}
        <br>
        <a href="{% url 'yaasapp:manage_auction' %}">{% trans "Manage auctions" %}</a>
    {% endif %}
    {% if user.is_superuser %}
        <br>
        <a href="{% url 'yaasapp:email_history' %}">{% trans "Email history" %}</a>
    {% endif %}
    {% if user.is_authenticated %}
    <br>
    <a href="{% url 'yaasapp:change_password' %}">{% trans "Change password" %}</a>
    {% endif %}
    {% if user.is_authenticated %}
    <br>
    <a href="{% url 'yaasapp:create_auction' %}">{% trans "Create auction" %}</a>
    {% endif %}
    <br>
    <a href="{% url 'yaasapp:active_auction_list' %}">{% trans "All active auctions" %}</a>
    <br>
    <a href="{% url 'yaasapp:search_auction_by_title' %}">{% trans "Search auctions by title" %}</a>
{% endblock %}

templates/not_allowed.html
<!-- templates/home.html -->
{% extends './base.html' %}
{% load i18n %}

{% block content %}
    <a href="{% url 'home' %}">{% trans "Home" %}</a>
    <br>
    <p>You are not allowed to access this ressource.</p>
{% endblock %}